### ISSUE TITLE
Should `withScheduler` yield `NonEmpty`?

### ISSUE THREAD

**Issue by fosskers** [lehins/haskell-scheduler#6]
For when we don't intend to keep any results, we use `withScheduler_` and get back `()` anyway. Otherwise, we expect some definitive result. In the case where we used `terminateWith`, the supplied extra value appears first (and indeed as the only) value in the result list. 

Quick proof as a `tasty` test:
```haskell
terminateOrder :: Assertion
terminateOrder = do
    r <- withScheduler Par' $ \sch -> do
        scheduleWork sch (threadDelay 5000000 >> pure 1)
        scheduleWork sch (terminateWith sch 10)
    head r @?= (10 :: Int)
```
So, provided that `withScheduler` actually returns, the result list will always have a value. In that case, should the return type not be `NonEmpty`? In my case specifically it would allow me to confidently use `NEL.head` in a parallel search algorithm whose value I actually want to use.

Thoughts?

**Comment by lehins** [comment]
Yeah I thought about that. I don't think `NonEmpty` is the correct type here though. Consider this 
```haskell
withShcheduler Seq $ \ _ -> pure ()
```
above will return an empty list, since nothing was scheduled.

The reason why I kept it as a list was for backwards compatibility and as a convenience, since `teminate*` functions are not the common usage.

What I was thinking of doing though is adding an extra function:
```haskell
withSchedulerResults :: MonadUnliftIO m => Comp -> (Scheduler m a -> m b) -> m (b, Either a [a])
```
Which would allow for getting the result of the scheduling action `b` as well as distinguishing between result of `terminateWith` (which is a `Left`) and the normal result `Right [a]`. Then I realized that it doesn't describe early termination with `terminate`, so I came up with this:
```haskell
data Results a
  = Finished [a] -- Finished with all scheduled jobs
  | FinishedEarly (NonEmpty a) -- ^ Finished early. Head is the value supplied to `terminate`
  | FinishedEarlyWith a -- ^ Finished with `teminateWith`

withSchedulerResults :: MonadUnliftIO m => Comp -> (Scheduler m a -> m b) -> m (b, Results a)
```

I think above takes care of handling of results of scheduled jobs, but the returned `b` poses a problem, since now nothing prevents a user from returning the scheduler itself, which would be incorrect:
```haskell
(scheduler, _) <- withSchedulerResults Par pure
```
The returned `scheduler` is useless and simply won't work. So I came up with a solution for that as well. But that solution requires adding extra phantom type variable which will cause some breaking changes, so I am contemplating if it is all worth it:
```haskell
data Scheduler c m a = ...

withScheduler :: MonadUnliftIO m => Comp -> (forall c . Scheduler c m a -> m b) -> m [a]

withSchedulerResults :: MonadUnliftIO m => Comp -> (forall c . Scheduler c m a -> m b) -> m (b, Results a)
```

What do you think about all that? Naming is still not set in stone.

**Comment by fosskers** [comment]
> above will return an empty list, since nothing was scheduled.

Woops!

```haskell
 | FinishedEarly (NonEmpty a) -- ^ Finished early. Head is the value supplied to `terminate`
```
But from the docs of `terminate`:

> and collect whatever results have been computed, with supplied element guaranteed to being the **last** one.
 
I probably prefer it being at the head, the same as `terminateWIth`.

> now nothing prevents a user from returning the scheduler itself, which would be incorrect:

I'm having trouble attempting that with the current `scheduler`:
```haskell
foop :: IO [a]
foop = withScheduler Par' pure

zoop :: IO [Scheduler IO a]
zoop = withScheduler Par' $ \sch -> scheduleWork sch (pure sch)
```
`foop` compiles fine, but `zoop` fails with:
```
    • Occurs check: cannot construct the infinite type:
        a ~ Scheduler IO a
      Expected type: IO (Scheduler IO a)
        Actual type: IO (Scheduler IO (Scheduler IO a))
```

Overall though, I'd definite appreciate something like `withSchedulerResults`.

**Comment by lehins** [comment]
You are right on this:
> But from the docs of terminate:

In order to disambiguate it I'll do this:
```haskell
  | FinishedEarly [a] a
```
I made it to return it as last element of the list in general case, cause it is really the last computation that happens, so it feels like it should be last, so I think for backwards compatibility I'll keep it last. It doesn't really matter since with this `Results` data type it will be clear which element it is.

Currently you can't get the scheduler out of `withScheduler :: MonadUnliftIO m => Comp -> (Scheduler m a -> m b) -> m [a]` function, because the result of the scheduling function `b` is being ignored and the type system prevents you from creating an infinite type. Although there is a trick that can be used to work around this safety measure:
```haskell
λ> newtype EscapedScheduler e = EscapedScheduler (Scheduler IO (EscapedScheduler e))
λ> [EscapedScheduler escaped] <- withScheduler Par' (\ scheduler -> scheduleWork scheduler $ pure (EscapedScheduler scheduler))
```
But the escaped scheduler is pretty useless:
```haskell
λ> :t escaped
escaped
  :: Scheduler IO (EscapedScheduler ghc-prim-0.5.3:GHC.Types.Any)
```
In any case, it is pretty tricky to get it done in the first place, and that is intentional. On the other hand if I add (note a tuple and returned `b`):

```haskell
withSchedulerResults :: MonadUnliftIO m => Comp -> (Scheduler m a -> m b) -> m (b, Results a)
```
Then, without using `RankNTypes` it is trivial to extract a non working scheduler:
```haskell
λ> (escaped, _) <- withSchedulerResults Par' (\ scheduler -> scheduleWork (scheduler) (pure True) >> pure scheduler)
λ> :t escaped
escaped :: Scheduler IO Bool
λ> scheduleWork escaped (print "Will never run" >> pure undefined)
```

I think I will add this in the next minor version `scheduler-1.4.2`  and upload it to hackage in the next couple of days.
```haskell
withSchedulerResults :: MonadUnliftIO m => Comp -> (Scheduler m a -> m b) -> m (Results a)
```
This way we have this functionality in current lts-14.

I will also will make a new release, `scheduler-1.5.0` that will have this extra type parameter on the scheduler, but I'll think a bit more about it.

**Comment by fosskers** [comment]
I'm happy with `m (Results a)`. That seems to me to be the happy middle-ground. The scheduler shouldn't be able to escape that way (without the extra effort that you demonstrated, of course).

**Comment by lehins** [comment]
@fosskers Thanks for your feedback. I made a release on hackage earlier today.
