### ISSUE TITLE
`Results` follow-up

### ISSUE THREAD

**Issue by fosskers** [lehins/haskell-scheduler#8]
Thanks for the new release! Now that I'm using the new type, I can comment more on how it feels to use it.

What was previously:
```haskell
    fuz :: IO Int
    fuz = do
      r <- fmap head . withScheduler comp $ \sch ->
        scheduleWork sch $ terminateWith sch (1 :: Int)
      pure r
```
is now
```haskell
    fuz :: IO Int
    fuz = do
      r <- withSchedulerR comp $ \sch ->
        scheduleWork sch $ terminateWith sch (1 :: Int)
      case r of
        FinishedEarlyWith i -> pure i
        FinishedEarly _ i -> pure i
        Finished (i:_) -> pure i
        _ -> error "crap?"
```
or just
```haskell
    fuz :: IO Int
    fuz = do
      r <- withSchedulerR comp $ \sch ->
        scheduleWork sch $ terminateWith sch (1 :: Int)
      case r of
        FinishedEarlyWith i -> pure i
        _ -> error "crap?"
```
Either way, I'm still left with the non-totality, even though we *know* that a single result will exist due to the `terminateWith`. Is there a way to signal this through type signatures instead? Say `Scheduler (k :: TerminationScheme) m a` or similar, such that I'm guaranteed to get my single value out?

**Comment by lehins** [comment]
The problem is that you are calling `error` rather than handling the result of the computation. You are thinking of it as:

```haskell
fux :: Int
fux = case Just 5 of
  Just i -> i
  _ -> error "crap?"
```

You know for sure by looking at the code that it will never throw "crap?" and will always return `5`, in fact compiler might even optimize it away, cause the computation is pure and provable. But that is not always the case for. Basically, what you are suggesting is simply undecidable. For example, what would be your guess the result of this computation would be?

```haskell
    fuz :: Int -> IO Int
    fuz i = do
      r <- withSchedulerR Par $ \sch ->
        replicateN (i + 1) (pure (i + 1))
        when (even i) $ scheduleWork sch $ terminateWith sch (1 :: Int)
        when (even (i `div` 2)) $ scheduleWork sch $ terminate sch (2 :: Int)
        replicateN i (pure i)
      case r of
        Finished is -> pure is
        FinishedEarly is i -> pure $ i : is
        FinishedEarlyWith i -> pure [i]
```
That's right, it depends on the input. But even if I tell you the input is `4` there is no way to tell with 100% certainty what the output will be.

What about this?

```haskell
    fuz :: IO Int
    fuz isMoonBlue = do
      r <- withSchedulerR comp $ \sch -> do
        isMoonBlue <- read <$> readFile "moon.txt"
        unless isMoonBlue $ scheduleWork sch $ terminateWith sch (1 :: Int)
      case r of ...
```
What will `r` be? Once in a blue moon it might be `Finished []` ;)

At the same time, if you are 100% sure your algorithm will hit the branch that calls `terminateWith`, then there is nothing wrong with using a partial function and calling it "Impossible", in fact, if your algorithm is side effect free and doesn't break referential transparency, than you could even safely wrap it in `unsafePerormIO` and make a pure function out of it.

But it is truly impossible for me to know at the type level what your IO computation will do at runtime (compile time IO is doable with template haskell, but that is a different story)

**Comment by fosskers** [comment]
Okay, I understand the issue a bit better now, thanks.
